### ISSUE TITLE
Support using label selector to determine to which nodes a BGP peer applies.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#112]
Considering changing the BGP peering configuration model.  At the moment peers are configured as global resources or node specific resources.

A global resource is a peer that peers with every node in the cluster.
A node specific resource is a peer that only peers with the node.

The global peers are not really that useful outside a test deployment.  That means in most real world deployments you'd configure node specific peers.  However, consider a particular RR in a cluster - you need to consider the node-specific peer config for every node that peers with that RR.

I'd prefer to change the peering model as follows:
-  Nodes would have a set of labels.
-  BGP Peers would no longer be "global" or "node specific".  They instead become their own resource type representing an actual peer.   A selector field on the peer selects which nodes it peers with.  To mimic a "global" peer you can just use an "all()" selector.  The BGP peers would be identified by name rather than IP address.  The IP address would move in to the BGP spec.

```
apiVersion: v1
kind: node
metadata:
  name: node1
  labels:
    rack: ax10
spec:
  bgp:
    ipv4Addr: 1.2.3.4
    ipv6Addr: aa::ff
    asNumber: 123456

apiVersion: v1
kind: bgpPeer
metadata:
  name: routerReflector1
spec:
  ipAddress: 1.3.4.5
  asNumber: 123456
  nodeSelector: rack=='ax10'
```
