### ISSUE TITLE
validation errors with `calicoctl apply` policy

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/libcalico-go#156]
With the latest commits for validation, `calicoctl apply` doesn't work as expected for the test yaml files in `test/` . Is the syntax for the yaml files different now or is this something wrong with the validation code? 

```bash
gunjan@mac:~/go/src/github.com/tigera/libcalico-go$ sudo ./bin/calicoctl apply --filename=test/policy.yaml
Error processing input file: error with field InterfaceName = ''
Error executing command: error with field InterfaceName = ''
```

similar policy I have for testing produces different validation errors: 

```yaml
- apiVersion: v1
  kind: tier
  metadata:
    name: tier1
  spec:
    order: 12.345
- apiVersion: v1
  kind: policy
  metadata:
    name: policy1
    tier: tier1
  spec:
    order: 9999.9999
    ingress:
      - action: nextTier
        icmp:
          type: 10
          code: 100
        source:
          tag: web
          net: 1.2.3.4/10
          selector:
          ports: [1,2,3,4]
        destination:
          tag: database
          net: 10.20.30.40/32
          selector:
          ports:
    egress:
      - action: deny
        protocol: tcp
        source:
          "!tag": abcd
          "!net": aa:bb:cc::ff/100
          "!selector": 
          "!ports": [100]
    selector:
```

```bash
gunjan@mac:~/go/src/github.com/tigera/libcalico-go$ sudo ./bin/calicoctl get --filename=test/testPol.yaml
Error getting resources: error with field source ports = '[{{0 1 }} {{0 2 }} {{0 3 }} {{0 4 }}]'
```

When I go back to the commit before this one: https://github.com/projectcalico/libcalico-go/commit/e7a8b74eee57ea4bc8ceee9534053bfc89f78e2e

same policies seem to work.
