### ISSUE TITLE
Port range gets interpreted incorrectly

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#186]
```
 {'apiVersion': 'v1',
  'kind': 'profile',
  'metadata': {'name': 'profile2'},
  'spec': {
      'egress': [{'action': 'allow',
                  'destination': {},
                  'source': {}}],
      'ingress': [{
                   'action': 'deny',
                   'protocol': 'tcp',
                   'source': {
                              'ports': ['10:20'],
                   }}],
  }},
```

If I send in the above profile and then request it back using `calicoctl get profile -o yaml`, I see that the `ports` has changed from that string to an `int` with value `620`.  Playing with the value and seeing what happens leads me to believe that something is interpreting this string as a Time and the 620 is the number of minutes since 00:00.  

@robbrockbank took a look and thinks that this is something to do with `json.Unmarshal`.  The unit tests currently don't test with `json.Unmarshal`...

**Comment by gunjan5** [comment]
@lwr20 I tried reproducing it with the latest golang branch, and I don't see it being converted to `620`, maybe I'm doing it wrong? 
See my output below:
```
{'apiVersion': 'v1',
  'kind': 'profile',
  'metadata': {'name': 'profile2'},
  'spec': {
      'egress': [{'action': 'allow',
                  'destination': {},
                  'source': {}}],
      'ingress': [{
                   'action': 'deny',
                   'protocol': 'tcp',
                   'source': {
                              'ports': ['10:20'],
                   }}],
  }}
```
```bash
$ ./bin/calicoctl apply -f bleh.json
Successfully applied 1 'profile' resource(s)
```
```yaml
$ ./bin/calicoctl get profile -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: profile2
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: deny
      destination: {}
      protocol: tcp
      source:
        ports:
        - "10:20"
```
