### ISSUE TITLE
calicoctl does not reject unexpected fields and stores a different rule to what the user intended

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#248]
If I use calicoctl to add this config (shown in python dict format):
```
{'kind': 'policy', 
'spec': {
    'ingress': [{'action': 'allow', 'source': {}, 'destination': {}, 'protocol': 'udp'}], 
    'egress': [{'action': 'deny', 'source': {}, 'destination': {}, 'protocol': 'tcp', 'ports': [10, 90, 65536]}], 
    'order': 100000, 'selector': ''}, 
'apiVersion': 'v1', 
'metadata': {'name': 'policy2'}}
```
It accepts it without an error.  It should error because 65536 is not a valid port number.  But what's been stored in etcd is:
```
{'kind': 'policy', 
'spec': {
    'ingress': [{'action': 'allow', 'source': {}, 'destination': {}, 'protocol': 'udp'}], 
    'egress': [{'action': 'deny', 'source': {}, 'destination': {}, 'protocol': 'tcp'}], 
    'order': 100000, 'selector': ''}, 
'apiVersion': 'v1', 
'metadata': {'name': 'policy2'}}
```
Which is a VERY different rule from the one that was intended...  

If the user notices, this is an irritation, if not, we've *silently broken their security policy*.

**Comment by lwr20** [comment]
A simpler repro:
```
$ cat test.yaml 
apiVersion: v1
kind: policy
metadata: {name: policy2}
spec:
  egress:
  - action: deny
    destination: {}
    ports: [10, 90, 65536]
    protocol: tcp
    source: {}
  ingress:
  - action: allow
    destination: {}
    protocol: udp
    source: {}
  order: 100000
  selector: ''

$ dist/calicoctl apply -f test.yaml 
Successfully applied 1 'policy' resource(s)

$ dist/calicoctl get policy -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: policy2
  spec:
    egress:
    - action: deny
      destination: {}
      protocol: tcp
      source: {}
    ingress:
    - action: allow
      destination: {}
      protocol: udp
      source: {}
    order: 100000
    selector: ""
```

**Comment by lwr20** [comment]
Ahhh!  My yaml is invalid, but not in the way I thought it was.  This is what I should have been using:
```
apiVersion: v1
kind: policy
metadata: {name: policy2}
spec:
  egress:
  - action: deny
    destination: {}
    source:
      ports: [10, 65536, 90]
      protocol: tcp
  ingress:
  - action: allow
    destination: {}
    protocol: udp
    source: {}
  order: 100000
  selector: ''
```

So the bug here is in fact that if you have an unknown field in your yaml, it gets dropped silently, which is still rubbish...  I'll update the title.

**Comment by wleese** [comment]
Here's another example, but rather of a 'wrong' error message:

```
- apiVersion: v1
  kind: profile
  metadata:
    labels:
      profile: local-a1-app
    name: local-a1-app
  spec:
    egress:
    - action: allow
    ingress:
    - action: allow
      destination:
        ports:
        - 80
      protocol: tcp
      source:
        selector: profile == 'local-a1-app'
```

When removing protocol:tcp the error message is:
```
Error processing input file: error with field destination ports = '[80]'
```
