### ISSUE TITLE
Config files should be versioned, have spec

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#252]
The datastore configuration files should have a version and a spec.

e.g

```
apiVersion: v1
kind: calicoConfig
spec:
  etcdEndpoints: <...>
```

Not beta worthy, but should be considered for v1.0

**Comment by robbrockbank** [comment]
```
apiVersion: v1
kind: calicoConfig
spec:
  etcdv2:
    etcdEndpoints: <...>
    ...
  kubernetes:
    kubeconfig: <...>
    ...  
```

So we'd expect only one of the
