### ISSUE TITLE
Can we give BGP Peers a name instead of using the IP address?

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#63]
Or does that not really fly?

**Comment by caseydavenport** [comment]
We can't get rid of the IP address, but having some sort of "tag" for the peer would be useful.

I think we need the IP address in the key (metadata), but maybe we can also have an optional Name field in the metadata (or "alias" field in the spec?) that allows users to tag with a human readable value.

**Comment by caseydavenport** [comment]
Something like this would be useful and low cost to implement: 

```yaml
apiVersion: v1
kind: BGPPeer
metadata:
  PeerIP: 1.2.3.4
spec:
  PeerAlias: tor1
```

No default value necessary for the PeerAlias field.
