### ISSUE TITLE
HostEndpoint InterfaceName doesn't work with vlan interfaces (bond0.<vlan-id>)

### ISSUE THREAD

**Issue by codertux** [projectcalico/libcalico-go#825]
I'm trying to create the following HostEndpoint:
```
- apiVersion: v1
  kind: hostEndpoint
  metadata:
    labels:
      k8s-role: master
    name: jd26-r36.xxx.eu-bond0.2103
    node: jd26-r36.xxx.eu
  spec:
    interfaceName: bond0.2103
```

## Expected Behavior
It should successfully create the endpoint.

## Current Behavior
```Failed to execute command: error with field interfaceName = 'bond0.2103'```

## Possible Solution
I've found the following: https://github.com/projectcalico/libcalico-go/blob/master/lib/validator/v1/validator.go#L45 and https://github.com/projectcalico/libcalico-go/blob/master/lib/validator/v3/validator.go#L65

I believe in both instances the regexp should be ```^[a-zA-Z0-9_\-\.]{1,15}$```

## Steps to Reproduce (for bugs)
1. Deploy the manifest in the description

## Context
Trying out the [Using Calico to Secure Host Interfaces](https://docs.projectcalico.org/v2.6/getting-started/bare-metal/bare-metal) guide. 

## Your Environment
* libcalico-go version: Not sure.
* Operating System and version: CentOS 7
```
# calicoctl version
Client Version:    v1.6.1
Build date:        2017-09-29T04:01:45+0000
Git commit:        1724e011
Cluster Version:   v2.6.2
Cluster Type:      kubespray,bgp
```
