### ISSUE TITLE
Proper error reporting when ICMP Code is specified without the Type

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/libcalico-go#94]
**Steps to reproduce:**
- Use this sample config yaml file: 
```yaml
- apiVersion: v1
  kind: tier
  metadata:
    name: tier1
  spec:
    order: 12.345
- apiVersion: v1
  kind: policy
  metadata:
    name: policy1
    tier: tier1
  spec:
    order: 9999.9999
    ingress:
      - action: nextTier
        icmp:
          code: 100
        source:
          tag: web
          net: 1.2.3.4/10
          selector:
          ports: [1,2,3,4]
        destination:
          tag: database
          net: 10.20.30.40/32
          selector:
          ports:
    egress:
      - action: deny
        protocol: tcp
        source:
          "!tag": abcd
          "!net": aa:bb:cc::ff/100
          "!selector": 
          "!ports": [100]
    selector:
```
- Not it has ICMP `code` specified without the `type`

**Current behavior:** 
```bash
./bin/calicoctl apply -f testprof.yaml
Error processing input file: error with field code = '100'
```

**Expeced behavior:** 
```bash
./bin/calicoctl apply -f testprof.yaml
Error processing input file: "icmpCodeWithoutType"
```

**Ref**: https://github.com/tigera/libcalico-go/blob/master/lib/api/rule.go#L62

Similar thing should be fixed for `NotICMP` too
