### ISSUE TITLE
Needs to clear NodeNetworkUnavailable flag on Kubernetes

### ISSUE THREAD

**Issue by aarnaud** [projectcalico/libcalico-go#944]
Same issue : https://github.com/projectcalico/canal/issues/74

## Expected Behavior
Calico has to update the `NetworkUnavailable` status on node

## Current Behavior
`NetworkUnavailable` stay to `True` and you can't use the node

## Possible Solution
Calico has to update the `NetworkUnavailable` status on node

## Steps to Reproduce (for bugs)
Use calico on GCE with `kubelet --cloudprovider=gce`

## Context
https://github.com/kubernetes/kubernetes/issues/44254
https://kubernetes.io/docs/concepts/architecture/nodes/#condition
https://github.com/weaveworks/weave/pull/3307

**Comment by aarnaud** [comment]
I'm working on a PR

**Comment by aarnaud** [comment]
Have to add new authorization on `calico-node` :

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-node
rules:
  - apiGroups: [""]
    resources:
      - nodes/status
    verbs:
      - patch
      - update
```
