### ISSUE TITLE
`calicoctl get policy` prints empty structs when the fields are not specified

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/libcalico-go#95]
**Steps to reproduce:**
- Use this config file:
```yaml
- apiVersion: v1
  kind: tier
  metadata:
    name: tier1
  spec:
    order: 12.345
- apiVersion: v1
  kind: policy
  metadata:
    name: policy1
    tier: tier1
  spec:
    order: 9999.9999
    ingress:
      - action: nextTier
        icmp:
          type: 10
          code: 100
        source:
          tag: web
          net: 1.2.3.4/10
          selector:
          ports: [1,2,3,4]
        destination:
          tag: database
          net: 10.20.30.40/32
          selector:
          ports:
    egress:
      - action: deny
        protocol: tcp
        source:
          "!tag": abcd
          "!net": aa:bb:cc::ff/100
          "!selector": 
          "!ports": [100]
    selector:
```
- apply the config 
- get the config with `calicoctl get policy`

**Note**: `destination` and `icmp` fields are not specified for `egress`

**Current behavior:**
```bash
      destination: {}
      icmp: {}
``` 

**Expected behavior:**
- Fields shouldn't be there at all in the `calicoctl get policy` output if they're not specified

**Code notes:**
- `omitempty` doesn't work with structs, so have to use struct pointers
- http://stackoverflow.com/questions/32643815/golang-json-omitempty-with-time-time-field
- did some basic trial and error, by sending `nil` when the fields are not specified, but it still prints empty `{}`, needs more troubleshooting
